### ISSUE TITLE
Hero image crop functionality does not work

### ISSUE THREAD

**Issue by arobillard** [Ingenium-Applied-Project/companion_app#41]
You may have mentioned that this is not complete yet, but I am confirming the crop functionality does not work in all browsers.

**Comment by lee00738** [comment]
Crop functionality should be fixed by tonight. Delayed due to me traveling .

**Comment by sous0049** [comment]
Adam (@arobillard) and Adesh (@shah0150), the crop functionality has been implemented.

It can be tested with the link (https://casm-companion-app.vercel.app/)

@lee00738 and @ulut0002 thank you for the help to implement and deploy this feature.

**Comment by sous0049** [comment]
Adam (@arobillard) and Adesh (@shah0150), the crop functionality has been implemented.

It can be tested with the link (https://casm-companion-app.vercel.app/)

@lee00738 and @ulut0002 thank you for the help to implement and deploy this feature.
