### ISSUE TITLE
Hero Image Tab -> Photo won't upload after 2 or 3 times. 

### ISSUE THREAD

**Issue by shah0150** [Ingenium-Applied-Project/companion_app#43]
See slack for video. https://ingeniumappli-3fb2184.slack.com/files/U06CYDKP54K/F06SUS6GQSK/screen_recording_2024-04-08_at_8.39.49___am.mov

**Comment by sous0049** [comment]
Hi Adesh (@shah0150) fixed as requested and in the main branch, you can test again with the link (https://casm-companion-app.vercel.app/) or by pulling the main branch.

In this case, the value in the input field is cached by some browsers in this case Chrome. To fix it, the property "key" was added to the input tag to keep track of rendering and cleaning of the field.
